### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/utz_tokens#2]
I am testing this out and it will be very useful. One improvement (I think) would be to make the format use Backdrop date formats, or an optional custom override. This would allow the admin to adjust the format in one place and have it adjust everywhere the tokens are used with that format immediately.

Spitballing, but maybe:

- `[utz-datetime:datetime|format]` where `format` is something like `medium` (referring to the Backdrop date format)
- `[utz-datetime:datetime|custom|D, m/d/Y - g:ia]` with an additional pipe for the custom string?

**Comment by laryn** [comment]
Or would it make sense to leave it as is, but check to see if the `format` matches any existing date format definitions, and if not treat is as custom?

**Comment by bugfolder** [comment]
Yes, I've already got a site using the current version, so need to preserve backward compatibility (if only for me ;o)), but checking for the existing formats first would make sense.

**Comment by bugfolder** [comment]
This is now implemented in [1.x-1.1.0](https://github.com/backdrop-contrib/utz_tokens/releases/tag/1.x-1.1.0).
