### ISSUE TITLE
Consider: when JS is enabled, use client-side for both anonymous and authenticated users

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/utz_tokens#3]
Current behavior is:
* When "detect anonymous" is not checked (or JS not available),
  * for authenticated users, server uses the user's time zone
  * for anonymous users, server uses the server time zone.
* When "detect anonymous" is checked,
  * for authenticated users, server uses the user's time zone.
  * for anonymous users, client-side code uses the browser's time zone.
 
For consistency, perhaps when "detect anonymous" is checked, everyone should get client-side/browser time zone. (And then change the name of the option to "detect all user's timezone" or something like that.)

This would address a situation where a block is cached with an anonymous-user, but then gets served up to an authenticated users.

Further thoughts solicited.

**Comment by laryn** [comment]
I think if a user has a timezone set, there are many cases where that is preferable to use. But I can see a desire for consistency as well -- can we give both options?

**Comment by bugfolder** [comment]
Sure, why not? Since that's the only setting on the settings page, we can afford to spend the words it will take to explain the difference.

**Comment by bugfolder** [comment]
This is now implemented in [1.x-1.1.0](https://github.com/backdrop-contrib/utz_tokens/releases/tag/1.x-1.1.0).
