### ISSUE TITLE
End date is showing even if it isn't set

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/utz_tokens#4]
I'm testing the field formatter and the field has the "Show start and end date" option selected. However for a particular instance there is no end date set -- it seems to be filling it in somehow anyway with an end date 4 hours later when displayed.

> ![Screen Shot 2021-05-04 at 12 21 59 PM](https://user-images.githubusercontent.com/871421/117043868-60f9e980-acd3-11eb-818d-462831d57f11.jpg)

> ![Screen Shot 2021-05-04 at 12 22 10 PM](https://user-images.githubusercontent.com/871421/117043897-6820f780-acd3-11eb-9a04-946ef5e35101.jpg)

**Comment by bugfolder** [comment]
Hi, can you provide some further information?

On the content type "Manage fields" page (which shows all of the fields for the type), which flavor of Date is it (e.g., "Date (Unix timestamp)" or one of the others)?

In the settings for the field, is "collect an end date" checked?

And then in the display settings, is "Display" set to "Both start and end dates"?

Last, if you change the display type from "UTZ Date and time" to ordinary "Date and time", do you also see the start and end times 4 hours apart, or something else?

**Comment by laryn** [comment]
The field in question: 

 - is a "Date" field (as opposed to "Date (ISO Format)" or "Date (UNIX timestamp)".
 - has "Collect an end date" selected but not required
 - is set to display "Start and End date" (but the events in question do not have an end date specified
 - I changed the display back to regular date and time (displaying both "Start and End date") and it only shows the start date as expected.

**Comment by bugfolder** [comment]
Thanks, very clear! Turns out UTZ Tokens didn't handle that case. (And also I found a bug in the timezone handling of the second date, which accounted for the 4-hour difference.) Would you try out the attached patch and let me know if it fixes your situation (pretty sure that it will).

[range_fix.patch.txt](https://github.com/backdrop-contrib/utz_tokens/files/6444167/range_fix.patch.txt)

**Comment by bugfolder** [comment]
Changes committed in https://github.com/backdrop-contrib/utz_tokens/commit/46a9b001adbd90ede881dfb781805cebbc8cf7bb.

**Comment by laryn** [comment]
@bugfolder Confirmed the patch solves it.

**Comment by bugfolder** [comment]
Great. It's now in the new release.
