### ISSUE TITLE
Question: how/where to do the tokens get replaced?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/utz_tokens#5]
In the module description it says:

> This module provides support for displaying a date or time in the user's own time zone in both formatted date fields and (via token text) within the body of any formatted text field.

How do the tokens get replaced in the body of the field? Do I need another module to allow token replacements?

**Comment by bugfolder** [comment]
> How do the tokens get replaced in the body of the field? Do I need another module to allow token replacements?

Yes, as the README file says in the **Tokens** section:

> To use the tokens in formatted text (the most common use case), install and enable the [Token Filter](https://backdropcms.org/project/token_filter) module.

Probably should add a line, though, saying "and then enable the 'Replace tokens' filter in your text format." Suggestions for clearer wording/description are welcome!
